In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
empty_array = np.empty(5, dtype= int)

In [6]:
empty_array

array([32530815,        0, 31756272, 31756352,       48])

In [8]:
np.empty([4,3])

array([[1.79964810e-316, 0.00000000e+000, 1.01855798e-312],
       [9.54898106e-313, 1.06099790e-312, 1.03977794e-312],
       [1.23075756e-312, 1.16709769e-312, 1.06099790e-312],
       [9.76118064e-313, 1.08221785e-312, 1.90979621e-312]])

In [10]:
a = ([4, 0.5, 20, 2], [11, 60, 4, 10])

In [11]:
a

([4, 0.5, 20, 2], [11, 60, 4, 10])

In [12]:
type(a)

tuple

In [13]:
array1 = np.array(a)

In [14]:
array1.dtype

dtype('float64')

In [15]:
array1.shape

(2, 4)

In [16]:
array1

array([[ 4. ,  0.5, 20. ,  2. ],
       [11. , 60. ,  4. , 10. ]])

In [17]:
array1[0,2]

20.0

In [18]:
array1[1]

array([11., 60.,  4., 10.])

In [20]:
np.zeros(10, dtype= int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
np.ones(3)

array([1., 1., 1.])

In [22]:
array1.size

8

In [23]:
array1.itemsize

8

In [24]:
np.info

<function numpy.info(object=None, maxwidth=76, output=None, toplevel='numpy')>

In [25]:
a

([4, 0.5, 20, 2], [11, 60, 4, 10])

In [27]:
b = np.array(2, dtype= int)

In [29]:
array1 * b
#br

array([[  8.,   1.,  40.,   4.],
       [ 22., 120.,   8.,  20.]])